channels:
  - defaults
  - conda-forge
dependencies:
  - awscli
  - flake8==3.5.0
  - flake8-import-order==0.17
  - flake8-quotes==1.0.0
  - ipython
  - python=3.7.0
  - pip:
    - flake8-commas==2.0.0
