version: 2.1
jobs:
  build-and-test:
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - run:
          name: Build project
          command: deploy-scripts/build-env.sh
      - run:
          name: Python linting
          command: flake8
          when: always
      - run:
          name: Shellcheck
          command: ./deploy-scripts/shellcheck.sh
          when: always
    deploy-production:
      docker:
        - image: continuum/miniconda3:latest
      steps:
        - checkout
        - attach_workspace:
            at: ~/project
        - run:
            command: deploy-scripts/deploy.sh lambda-ew1-p-demo-api
workflows:
  version: 2.1
  build-containerise-deploy:
    jobs:
      - build-and-test
      - deploy-production:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master